### ISSUE TITLE
cant acces other than from local host 

### ISSUE THREAD

**Issue by andlo** [OpenVoiceOS/ovos-personal-backend-ui#5]
No matter what I try I cant acces the backend manager from network - only n the machine it selv :(

works http://127.0.0.1:36535/

but from other pc it fails.

Is it something in a config I have missed or could it be something else ?

**Comment by JarbasAl** [comment]
i think we need to pass host=0.0.0.0 here https://github.com/OpenVoiceOS/ovos-backend-manager/blob/d56534e8a39137e0aa4ec714a88708b1dca8bf84/ovos_backend_manager/app.py#L53

**Comment by andlo** [comment]
Great - I test that and if it works Ill PR.

**Comment by JarbasAl** [comment]
closed by #6
